[dev]
  command = "cameronjs dev"
  publish = "publish"
  port = 8080

[build]
  command = "yarn build"
  publish = "publish"
  functions = "functions"

[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[context.production]
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/"
  to = "/v1/en"
  force = true
  headers = { X-From = 'Netlify' }

[[redirects]]
  from = "/v1"
  to = "/v1/en"
  force = true
  headers = { X-From = 'Netlify' }

[[headers]]
# see https://www.netlify.com/docs/headers-and-basic-auth
