[build]
  command = "yarn build"
  publish = "public"
  functions = "functions"

[context.production]
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/"
  to = "/v1"
  force = true
  headers = { X-From = 'Netlify' }

[[headers]]
# see https://www.netlify.com/docs/headers-and-basic-auth
